config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users
  resources :books, only: [:create, :destroy]

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :email, email: true, presence: true, uniqueness: {allow_blank: true}

  after_create :send_welcome_email

  def send_welcome_email
    AdminMailer.delay.new_user(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.js { }
        format.html { redirect_to @book.user, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.js { render status: :unprocessable_entity }
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.destroy
        format.js { }
        format.html { redirect_to @book.user, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      begin
        @user = User.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to(root_url, :notice => 'User could not be found')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<div class="add_book_form">
  Add a book for <%= user.name %>
  <%= simple_form_for(book, url: books_path, remote: true, html: {class: 'add_book'}) do |f| %>
    <%= f.hidden_field :user_id, value: user.id %>
    <%= f.input :title %>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/books/_list.html.erb
<div class="books_list">
  <p>
    <strong>Books:</strong>
    <ul>
      <% if books.any? %>
        <% books.each do |book| %>
          <%= render partial: '/books/list_item', locals: { book: book } %>
        <% end %>
      <% end %>
    </ul>
  </p>
</div>

app/views/books/_list_item.html.erb
<li class="book_id_<%= book.id %>">
  <%= book.title %>
  <%= link_to 'Destroy', book_path(book), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
</li>

app/views/books/create.js.erb
<% if @book.errors.any? %>
  $(".add_book_form").replaceWith('<%= j render partial: "/books/form", locals: { user: @book.user, book: @book } %>');
<% else %>
  // lets make sure we remove all errors
  // incase validation failed last time
  $('.error, .error_notification').remove();
  $("div.input").removeClass( "field_with_errors" );

  $(".books_list ul").append('<%= j render partial: "list_item", locals: { book: @book } %>');
  $('form.add_book input#book_title').val('');
<% end %>

app/views/books/destroy.js.erb
$('.books_list ul li.book_id_<%= @book.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <div id="notice">
    <%= msg %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/_book_form.html.erb
Add a book for <%= user.name %>
<%= simple_form_for(book, url: create_book_user_path(user.id)) do |f| %>
  <%= f.hidden_field :user_id, value: user.id %>
  <%= f.input :title %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :email %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= render partial: '/books/list', locals: { books: @user.books } %>
<%= render partial: '/books/form', locals: { user: @user, book: @user.books.new } %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>